### ISSUE TITLE
Build fails against freeimage 3.15.1

### ISSUE THREAD

**Issue by lambdafu** [SemanticsOS/smc.freeimage#1]
Hi there,

I'm trying to get smc.freeimage to install on Ubuntu.  The main hurdle seems to be the version of libfreeimage.  Ubuntu has 3.15.1, whereas it looks like smc.freeimage requires 3.15.3 (I haven't checked 3.15.2).

The issue is the three 64-bit FIDT_\* constants FIDT_LONG8, FIDT_SLONG8 and FIDT_IFD8.  These constants don't exist at all in 3.15.1, and that causes smc.freeimage to bail when it tries to build ficonstants.c:

smc/freeimage/ficonstants.c:205:46: error: 'FIDT_LONG8' undeclared (first use in this function)
smc/freeimage/ficonstants.c:206:47: error: 'FIDT_SLONG8' undeclared (first use in this function)
smc/freeimage/ficonstants.c:207:45: error: 'FIDT_IFD8' undeclared (first use in this function)

If I comment out those three lines from ficonstants.c, pip builds the package successfully, but the resultant module then fails to import.

If the 3.15.3 version of freeimage were available as an Ubuntu package, I'd just upgrade to it, but it seems that there is really nothing more recent than 3.15.1.  There's a bug report in Launchpad [1] to bump the version but 3.15.3 has been out for six months already, so I'm not holding my breath on that one.

I'm probably going to roll my own version of libfreeimage, but I thought it would be worth asking where there is a way that smc.freeimage could support building against 3.15.1.

Thanks for your time.

[1] https://bugs.launchpad.net/ubuntu/+source/freeimage/+bug/1057201

---
- Bitbucket: https://bitbucket.org/tiran/smc.freeimage/issue/1
- Originally Reported By: [Brendan Jurd](http://bitbucket.org/direvus)
- Originally Created At: 2012-11-29T06:56:04.233

**Comment by lambdafu** [comment]
Well I got the static build to install, but it can't be imported.

```
  >>> import smc.freeimage
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "smc/freeimage/__init__.py", line 32, in <module>
      from smc.freeimage import _freeimage
  ImportError: cannot import name _freeimage
```

By the way, you're probably already aware of this but smc.freeimage doesn't build against the latest LCMS release 2.4.  It only builds against 2.3.  In 2.4 they seem to have gotten rid of the constants XYZA_*.  I realise that INSTALL.txt lists LCMS 2.3 as the requirement, but I thought I'd give the latest version a try anyway.

On the other hand, building against the latest FreeImage 3.15.4 doesn't seem to be a problem, even though the INSTALL.txt specifically lists 3.15.3 as a requirement.  So you can probably update the INSTALL doc to say 3.15.{3,4}.

Seems that installing stuff on Ubuntu is easy, except when it's not ... and then it's REALLY not.  Whereas I just ran `pip install smc.freeimage` on gentoo and it worked first time.

---

Original Comment By: [Brendan Jurd](http://bitbucket.org/direvus)

**Comment by lambdafu** [comment]
Okay, thanks for the reply Christian.  I will give the static build a go.

---

Original Comment By: [Brendan Jurd](http://bitbucket.org/direvus)

**Comment by lambdafu** [comment]
Thanks for your detailed bug report. I'm fear you can't use FreeImage from Ubuntus repositories. It's not just the version. Debian/Ubuntu are doing some rather nasty things to the library which causes all sorts of trouble.

FreeImage not even wraps but also contains the sources of all its dependencies. It's really convenient as one doesn't need to compile and install them. However Debian/Ubuntu heavily patches FreeImage to use the system-wide libraries instead of the internal ones. They don't do it properly, too. :( For example the test suite fails with a floating point exception in libjpeg's jdiv_round_up() like [1] .

I've implemented static builds to get around those kinds of issues. It's documented in INSTALL.txt. I suggest that you get my FreeImageTurbo branch for a static builds

[1] https://bugs.kde.org/show_bug.cgi?id=229476

---

Original Comment By: [Christian Heimes](http://bitbucket.org/tiran)
